# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Unit testing"
      lane :unit_test do
        build_android_app(task: "clean")
        build_android_app(task: "test")
  end

  desc "Instrumentation testing"
      lane :ui_test do
        build_android_app(task: "clean")
        build_android_app(
          task: 'assemble',
          build_type: 'DevDebug'
        )
        build_android_app(
          task: 'connected',
          build_type: 'DevDebug'
        )
  end

  desc "Build beta version"
    lane :beta do
      build_android_app(task: "clean")
      build_android_app(
          task: 'bundle',
          flavor: 'beta',
          build_type: 'Release',
          properties: {
               "android.injected.signing.store.file" => ENV['STORE_FILE'],
               "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
               "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
               "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
            }
      )
  end

  desc "Deploy Beta to the Google Play"
    lane :beta_googleplay do
      upload_to_play_store(
          release_status: 'draft',
          track: 'beta',
          aab: 'app/build/outputs/bundle/betaRelease/app-beta-release.aab',
          skip_upload_screenshots: true,
          skip_upload_images: true
      )
  end

  desc "Build production version"
    lane :prod do
      build_android_app(task: "clean")
      build_android_app(
        task: 'bundle',
        flavor: 'prod',
        build_type: 'Release',
        properties: {
            "android.injected.signing.store.file" => ENV['STORE_FILE'],
            "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
            "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
            "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
            }
      )
  end

  desc "Deploy Production to the Google Play"
    lane :prod_googleplay do
        upload_to_play_store(
            release_status: 'draft',
            track: 'production',
            aab: 'app/build/outputs/bundle/prodRelease/app-prod-release.aab',
            skip_upload_screenshots: true,
            skip_upload_images: true
    )
  end

end
